### PR TITLE
Various cleaning and better practices

### PR DESCRIPTION
**Pull request by vinceh121**
Changes:

- Removed unused imports
- Removed useless `@SuppressWarnings`
- Added full serialUIDs when missing
- Un-duplicated utility nested null-check in unit tests
- Prepared for better practices regarding exceptions in internal authentication process

Notes on breaking API changes:

I would recommend switching from APIs that return booleans on failure to throwing exceptions. Not done in this PR as it would be an API breaking change.

### CODE REVIEW

**Review by LelouBil — COMMENTED** [review]
Are you sure SerialVersionUUIDs are needed in Date**Deserializer**, CDT**Deser** and Lesson**Deserializer** ? Those are the classes that deserialize, not the actual serialized object. But maybe I'm missing something with Jackson.

**Comment by LelouBil** [comment]
Also, for the exceptions you could add a try/catch in login for now and migrate all sub methods to throwing exceptions, this would not be a breaking change but still would be 3/4 of the steps needed.

**Comment by vinceh121** [comment]
You are right about the serial IDs in the deserializers, they do seem pointless, however it is recommended for the Exceptions.

try/catch in login done in 8554a7a

**Review by LelouBil — APPROVED** [review]
I think some of the exception types will change but either way thanks for the PR, everything looks good to me 👍

**Pull request merged**
